### ISSUE TITLE
pip install failures

### ISSUE THREAD

**Issue by naisanzaa** [jmcarpenter2/swifter#173]
I recently started having `swifter` pip install failures. 

It works if I run `pip3 install -U numpy pandas pandas>=1.1.5 numpy>=1.22.2 dask>=2022.1.1 tqdm psutil` before `grep -v '^#' requirements.txt | xargs python3 -m pip install -U`

But I don't understand why

The `xargs` should be installing the required packages before `swifter`?

And before, I was just installing with `python3 -m pip install -U -r requirements.txt` and it was working fine. 

requirements.txt
```shell
...
# datascience
pandas>=1.1.5
jupyterlab>=3.1.9
numpy>=1.22.2
dask>=2022.1.1
tqdm>=4.62.3
swifter>=1.1.1
...
```

ci.yml
```shell
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
#      - run: pip3 install -U numpy pandas pandas>=1.1.5 numpy>=1.22.2 dask>=2022.1.1 tqdm psutil
      - name: Install python packages
        run: grep -v '^#' requirements.txt | xargs pip3 install -U
```

https://github.com/TheShellLand/automonisaur/runs/5089991392?check_suite_focus=true
```shell
Collecting numpy>=1.22.2
  Downloading numpy-1.22.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 57.1 MB/s eta 0:00:00
Collecting dask>=2022.1.1
  Downloading dask-2022.1.1-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 62.0 MB/s eta 0:00:00
Collecting tqdm>=4.62.3
  Downloading tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.2/76.2 KB 18.5 MB/s eta 0:00:00
Collecting swifter>=1.1.1
  Downloading swifter-1.1.1.tar.gz (633 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 633.1/633.1 KB 51.8 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-fifafnqu/swifter_09eb726c6b204f0a8f[46](https://github.com/TheShellLand/automonisaur/runs/5089991392?check_suite_focus=true#step:4:46)5d3690df00ce/setup.py", line 2, in <module>
          from swifter import __version__ as VERSION
        File "/tmp/pip-install-fifafnqu/swifter_09eb726c6b204f0a8f4[65](https://github.com/TheShellLand/automonisaur/runs/5089991392?check_suite_focus=true#step:4:65)d3[69](https://github.com/TheShellLand/automonisaur/runs/5089991392?check_suite_focus=true#step:4:69)0df00ce/swifter/__init__.py", line 5, in <module>
          from .swifter import SeriesAccessor, DataFrameAccessor
        File "/tmp/pip-install-fifafnqu/swifter_09eb[72](https://github.com/TheShellLand/automonisaur/runs/5089991392?check_suite_focus=true#step:4:72)6c6b204f0a8f465d3690df00ce/swifter/swifter.py", line 3, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by naisanzaa** [comment]
Okay fixed using `xargs -L1` (to split the lines)

But still doesn't explain why `python3 -m pip install -U -r requirements.txt` was working fine before

**Comment by jtmiclat** [comment]
Did some investigating, if you pin the version to `swifter==1.0.9` it should work for now. 

The culprit seems to be in setup.py importing the library before installing anything. 
https://github.com/jmcarpenter2/swifter/blob/32c744055d16f527b4448d9599680c5c5c8d0eeb/setup.py#L2 

Within the `swifter/__init__.py`, it imports some modules that causes the situation where you need all the dependency before you can install the package.

https://github.com/jmcarpenter2/swifter/blob/32c744055d16f527b4448d9599680c5c5c8d0eeb/swifter/__init__.py#L2-L10

**Comment by dlangerm** [comment]
I'm getting this error suddenly too.

**Comment by jmcarpenter2** [comment]
Thanks for raising this! I will fix this immediately. Apologies!
